language: ruby
rvm:
 - 2.5.3
env:
- CI=true
services:
  - redis-server
  - postgresql
cache: bundler
before_install:
  - gem install bundler -v 1.15.2
before_script:
  - psql -c 'create database glowfic_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rails db:migrate --trace
  - bundle exec rspec spec
branches:
  only:
  - master
addons:
  code_climate:
    repo_token: 1e0c6dba9930e839038860b6d73301226c821937f57ed35d06fc0e4b7bddf5f6
after_success:
  - bundle exec codeclimate-test-reporter
