x-env: &env
  REDIS_URL: redis://redis
  GLOWFIC_DATABASE_HOST: postgres
  GLOWFIC_DATABASE_USER: postgres
  GLOWFIC_DATABASE_PASS: postgres
  AWS_ACCESS_KEY_ID: glowfic_minio
  AWS_SECRET_ACCESS_KEY: glowfic_minio
  S3_BUCKET_NAME: glowfic-dev
  MINIO_ENDPOINT: http://minio:9000/
  MINIO_ENDPOINT_EXTERNAL: http://localhost:9000/
  ACCOUNT_SECRET: secret
x-svc: &svc
  build: .
  image: glowfic
  links:
    - redis
    - postgres
    - minio
  volumes:
    - .:/code:z
    - bundler-volume:/usr/local/bundle
    - webdrivers:/root/.webdrivers # caches webdrivers for selenium feature specs

services:
  web:
    <<: *svc
    ports:
      - 3000:3000
    command: bin/with-bundle bin/rails s
    environment:
      <<: *env
      BIND_HOST: 0.0.0.0
      # allow accessing the server from backstop
      RAILS_DEVELOPMENT_HOSTS: web:3000
  worker:
    <<: *svc
    command: bin/with-bundle rake resque:work
    environment:
      <<: *env
      TERM_CHILD: 1
      RESQUE_TERM_TIMEOUT: 7
      QUEUES: mailer,notifier,high,*
  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  minio:
    image: minio/minio
    command: server /data
    environment:
      - MINIO_ROOT_USER=glowfic_minio
      - MINIO_ROOT_PASSWORD=glowfic_minio
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data

volumes:
  bundler-volume:
  postgres-data:
  webdrivers:
  minio-data:
